CREATE TABLE IF NOT EXISTS public.bse_data (
  id BIGSERIAL PRIMARY KEY,
  application_id BIGINT NOT NULL,
  transaction_code VARCHAR(1),
  client_type VARCHAR(3),
  status VARCHAR(2),
  category VARCHAR(10),
  client_code VARCHAR(50),
  pan_no VARCHAR(10),
  political_ex_person VARCHAR(1),
  address1 TEXT,
  permn_equal_corp VARCHAR(1),
  address2 TEXT,
  country VARCHAR(50),
  state VARCHAR(100),
  city VARCHAR(100),
  pincode VARCHAR(10),
  type_of_service VARCHAR(5),
  contact_details VARCHAR(5),
  email VARCHAR(255),
  mobile_number VARCHAR(15),
  std_code VARCHAR(10),
  phone_no VARCHAR(20),
  depository_name1 VARCHAR(10),
  demat_id1 VARCHAR(20),
  depository_participant1 VARCHAR(20),
  bank_name1 VARCHAR(255),
  account_no1 VARCHAR(50),
  provide_details VARCHAR(10),
  income VARCHAR(50),
  net_worth VARCHAR(100),
  is_active VARCHAR(1),
  first_name VARCHAR(100),
  middle_name VARCHAR(100),
  last_name VARCHAR(100),
  aadhaar_card_no VARCHAR(20),
  date_of_birth VARCHAR(10),
  client_name VARCHAR(150),
  whether_corporate VARCHAR(1),
  number_of_directors INTEGER,
  is_poa VARCHAR(1),
  poa_for_fund VARCHAR(1),
  poa_for_security VARCHAR(1),
  per_country VARCHAR(50),
  per_state VARCHAR(100),
  per_city VARCHAR(100),
  per_pincode VARCHAR(10),
  opted_for_nomination VARCHAR(1),
  beneficial_own_acnt_no1 VARCHAR(20),
  opted_for_upi VARCHAR(2),
  bank_branch_ifsc_code1 VARCHAR(20),
  primary_or_secondary_bank1 VARCHAR(1),
  primary_or_secondary_dp1 VARCHAR(1),
  request_payload JSONB,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_bse_data_application_id UNIQUE (application_id)
);
